### PR TITLE
Fix curlOptionInteger to curlMultiOptionInteger

### PR DESCRIPTION
**Pull request by pietermees**
Fix for https://github.com/JCMais/node-libcurl/issues/125

### CODE REVIEW

**Comment by JCMais** [comment]
Thanks for the fix @pietermees

**Comment by pietermees** [comment]
@JCMais any chance you could do a patch release for this?

**Comment by JCMais** [comment]
Yep, I will do one this Saturday

**Comment by pietermees** [comment]
Great, thanks!

**Comment by JCMais** [comment]
@pietermees  v1.3.2 on npm

**Pull request merged**
