### PR TITLE
added electron v6 to appveyor, travis & circleci

### PR DESCRIPTION
**Pull request by alex-sherwin**
based on how electron v5 support was added previously, added electron v6 support

### CODE REVIEW

**Comment by JCMais** [comment]
Thank you @alex-sherwin !

**Comment by alex-sherwin** [comment]
Thanks for taking the PR,

What are the chances of getting an npm release (even if it's an alpha/beta)?

My motive is to get pre-built binaries for electron v6 on OS X/Win/Linux available from the public NPM repos

**Comment by JCMais** [comment]
I will be able to do that someday this week, but cannot tell exactly which one 😄

**Comment by alex-sherwin** [comment]
Is there anything I can contribute to ease the process of getting out a beta/alpha on NPM?

**Comment by JCMais** [comment]
@alex-sherwin v2.0.2 with electron v6 binaries should be available on NPM 😄

**Comment by alex-sherwin** [comment]
Thanks @hellomd!

**Pull request merged**
